### ISSUE TITLE
[test] Dispatch test not ported to greentea framework

### ISSUE THREAD

**Issue by PrzemekWirkus** [ARMmbed/minar#10]
Gents

Please port this test case ([dispatchtest.cpp#L42](https://github.com/ARMmbed/minar/blob/master/test/dispatchtest.cpp#L42)) if possible to [greentea framework](https://github.com/ARMmbed/greentea/blob/master/docs/QUICKSTART.md#creating-a-simple-test-case-no-mocking) compatible solution.

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-979

**Comment by 0xc0170** [comment]
This can be closed

**Comment by autopulated** [comment]
Fixed by f8f44a08c24c8ad978d557f99ec99983ae4cea4a
