### ISSUE TITLE
minar loses scheduled callback if it misses the scheduling deadline

### ISSUE THREAD

**Issue by bremoran** [ARMmbed/minar#12]
It appears that, If a callback misses its scheduling deadline, it is never scheduled.  On periodic callbacks, this means that no future callbacks are scheduled.

In the example below, the `cb1` callback will not be scheduled after the first few `cb2` callback.

This appears to be affecting the uvisor hello-world example as well.

cc @AlessandroA @bogdanm @meriac @autopulated 

Minimum viable test case:

```C++
#include "mbed.h"
#include "minar/minar.h"

uint32_t cnt = 0;
void cb1() {
    printf(".");
}
void cb2() {
    cnt++;
    printf("%x\r\n",cnt & 0xf);
}

void app_start(int argc, char *argv[])
{
    static Serial pc(USBTX, USBRX);
    pc.baud(9600);
    minar::Scheduler::postCallback(cb2).period(minar::milliseconds(500));
    minar::Scheduler::postCallback(cb1).period(minar::milliseconds(1));
}

```

**Comment by simonqhughes** [comment]
ARM Internal Ref: IOTSFW-1077

**Comment by jrobeson** [comment]
did it used to work and then break? maybe you can bisect it.

**Comment by bremoran** [comment]
@jrobeson This is fairly fundamental, I don't believe that bisect will help.

**Comment by bremoran** [comment]
This problem appears to be coming from: https://github.com/ARMmbed/minar/blob/master/source/minar.cpp#L391

If ```now``` exceeds  ```last_dispatch``` and there is still a task in the queue that has a scheduled time of ```last_dispatch``` or earlier, that task can't be scheduled.

**Comment by bogdanm** [comment]
Thanks for the report! I'll take a look at this.

**Comment by autopulated** [comment]
the scheduler "now" never used to be updated to be greater than the last scheduled time if the scheduler was lagging.

As periodic callbacks are based on the originally scheduled time, rather than the current scheduler time  (to prevent drift) this might have always been a problem.

The best fix might be to emit a warning in this case, and fall back to the scheduler time (accepting some lag in the periodic callback: breaking the guarantee that it will always be called on average the right number of times in any period)

**Comment by bremoran** [comment]
@autopulated Having looked through that code more, I'm no longer convinced that my initial analysis is right.  I don't see how this fault could occur based on the scheduling time; that part appears correct to me.

**Comment by bremoran** [comment]
This issue may be related to https://github.com/ARMmbed/uvisor-helloworld/issues/24

**Comment by bremoran** [comment]
Here are the conditions for failure:

* Minar is lagging beyond the tolerance of a periodic callback (CB1), when it is scheduled.
* Minar has at least one other callback in the queue (CB2)
* ```CB2->call_before``` is later than ```CB1->call_before``` + ```CB1->next_interval```

When executing here: https://github.com/ARMmbed/minar/blob/master/source/minar.cpp#L390, minar will execute the first half of the branch, setting last_dispatch later than ```CB1->call_before + CB1->next_interval```.  Then, when execution reaches https://github.com/ARMmbed/minar/blob/master/source/minar.cpp#L462, the next instance of CB1 will be scheduled in the past.
