### ISSUE TITLE
link to examples in README involving FunctionPointer and Event is broken

### ISSUE THREAD

**Issue by jrobeson** [ARMmbed/minar#13]
It points to https://github.com/ARMmbed/mbed-sdk-private/blob/master/test/EventHandler/main.cpp

The quoted text is `(Many more examples involving FunctionPointer and Event can be found here)` since github doesn't seem to show line numbers for READMEs.

**Comment by simonqhughes** [comment]
ARM Internal Ref: IOTSFW-1079
