### ISSUE TITLE
roadmap for minar?

### ISSUE THREAD

**Issue by jrobeson** [ARMmbed/minar#14]
Where is minar going next?

**Comment by simonqhughes** [comment]
ARM Internal Ref: IOTSFW-1078

**Comment by hugovincent** [comment]
We have a few things in mind for the future, but (notwithstanding bugfixes) we're happy with it for the next couple of months and are going to be focusing on other areas of mbed OS... but we always love to get feedback from users! If there is anything in particular please do let us know (you can re-open this issue if you want). Two of the key things we're aiming for in 2016 is to introduce preemption and better power management support.
