### ISSUE TITLE
Question: Best was to clear a periodic task

### ISSUE THREAD

**Issue by scottjenson** [ARMmbed/minar#18]
I have the current task running periodically:

    minar::Scheduler::postCallback(blinky).period(minar::milliseconds(750));

If I wished to cancel this callback, what's the proper way to do that? minar::Scheduler.stop() is a bit too strong as it stops everything in the schedule queue. What I'm confused by is that the postCallback function doesn't appear to return a handle that I could use for a clear/cancel method.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1442

**Comment by scottjenson** [comment]
After poking around a bit more in the source, there appears to be a returned value that has a clear method but it appears to be private. This seems like a good thing to fix in the API.

**Comment by 0xc0170** [comment]
I modified blinky example to cancel a callback. You can get a handle when registering a callback, which can then be used to cancel a callback:

```
    minar::callback_handle_t callback = minar::Scheduler::postCallback(blinky).period(minar::milliseconds(500)).getHandle();
    minar::Scheduler::cancelCallback(callback);
```

**Comment by scottjenson** [comment]
Excellent, thank you
