### ISSUE TITLE
Test cases in /test directory should be in separate directories

### ISSUE THREAD

**Issue by PrzemekWirkus** [ARMmbed/minar#21]
Currently your test directory looks like this:

```
minar
|- complex_dispatch.cpp
|- dispatchtest.cpp
```

Good practice and preferred way of `/test` dir structure is to put each separate test case in separate sub-directory. 
Rationale: test may have in the future more files per test (both source C/C++, headers code).

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1820
