### ISSUE TITLE
Setting the RTC to a time in the past causes scheduling to run fast

### ISSUE THREAD

**Issue by c1728p9** [ARMmbed/minar#25]
Adjusting the RTC to a time in the past causes minar to start scheduling tasks to run faster than they should.  Minar seems stuck in this state until until a reset occurs.

This code exhibits the issue on a K64F:

```
#include "mbed-drivers/mbed.h"
bool time_reset;
time_t start_time;
uint32_t count;

static void blinky(void)
{
    time_t t = time(NULL);
    long integer_time = (long)t;

    // After 5 seconds adjust the time by 5 seconds
    if ((!time_reset) && (integer_time - (long)start_time > 5)) {
        time_reset = true;
        set_time(start_time);
        printf("Setting time to %li\r\n", (long)start_time);
    }

    count++;
    printf("Time: %li, Count %li\r\n", integer_time, count);
}

void app_start(int, char**)
{
    printf("hello world\r\n");
    time_reset = false;
    start_time = time(NULL);
    count = 0;
    minar::Scheduler::postCallback(blinky).period(minar::milliseconds(1000));
}

```

And produces the output:

```
hello world
Time: 2287, Count 1
Time: 2288, Count 2
Time: 2289, Count 3
Time: 2290, Count 4
Time: 2291, Count 5
Setting time to 2286
Time: 2292, Count 6
Time: 2286, Count 7
Time: 2286, Count 8
Time: 2286, Count 9
...
Time: 2295, Count 385
Time: 2295, Count 386
Time: 2295, Count 387
Time: 2295, Count 388
Time: 2295, Count 389
Time: 2295, Count 390
Time: 2295, Count 391
Time: 2295, Count 392
Time: 2295, Count 393
Time: 2295, Count 394
Time: 2295, Count 395
Time: 2295, Count 396
Time: 2295, Count 397
Time: 2295, Count 398
Time: 2295, Count 399
Time: 2295, Count 400
Time: 2295, Count 401
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1843

**Comment by marcuschangarm** [comment]
@c1728p9 That is "correct" behavior for minar. Minar thinks that the clock has overflown and that it hasn't been called in quite awhile, so it tries to catch up by repeatedly calling the callback. 

In what context do you need to set the RTC manually?

**Comment by c1728p9** [comment]
Thanks for the response @marcuschangarm .  A common use case I would expect is the RTC getting adjusted to match an internet time server.  This issue isn't a blocker for me.  It was something I noticed when tracking down an unrelated bug.  Maybe the correct solution is to make the lp_ticker / RTC keep an internal offset for minar.  That way if the RTC is adjusted, the time seen by minar does not change.  Let me know what you think.

**Comment by marcuschangarm** [comment]
@c1728p9 we've been talking about merging the functionality from https://github.com/ARMmbed/mbed-time into the RTC API. 

It keeps track of unix time using and offset to the real RTC value as you suggest.
