### ISSUE TITLE
Default callback tolerance is 50ms

### ISSUE THREAD

**Issue by bogdanm** [ARMmbed/minar#28]
When a callback is created without specifying a tolerance, the tolerance defaults to the "magic value" of 50ms:

https://github.com/ARMmbed/minar/blob/master/source/minar.cpp#L150

This isn't something most people would expect and it can break their scheduling mechanisms in some cases. We need to decide how we handle this:

- is it OK to have a non-zero default tolerance (which is something most people won't expect)?
- if so, what should be the value of the default tolerance?
- if the default tolerance won't be 0 in the end, this needs to be documented in big bold letters.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1883

**Comment by jrobeson** [comment]
this page https://docs.mbed.com/docs/getting-started-mbed-os/en/latest/Full_Guide/MINAR/ is pretty clear that the default value isn't 0

```
tolerance: how long before or after the desired execution time the event can run. This helps MINAR optimize power consumption. Please note that the default tolerance value - the one used if you do not specify one yourself - is not 0; the value is set in minar.cpp.
```

 but it also suggests that you have to look at the code to find it.

**Comment by betzw** [comment]
Is it an expected behavior that if the tolerance gets exceeded the event will not be generated anymore?
If yes, how can a user specify that the event should be executed in any case?

**Comment by bremoran** [comment]
@betzw Periodic events are rescheduled, regardless of the current minar lag.

**Comment by bremoran** [comment]
@bogdanm @autopulated, a non-0 default tolerance is necessary for efficient operation of minar. That's what enables the callback aggregation, which allows longer sleep periods and fewer wakeups.

Erring on the side of energy conservation would suggest larger default tolerance. Erring on the side of timing precision would suggest a lower default tolerance. Erring on the side of usability would suggest the easiest possible configuration of default tolerance.

I suggest that we add a new minar API:

```C++
minar::Scheduler::defaultTolerance();
```

This could be initialized to ```YOTTA_CFG_MINAR_DEFAULT_SCHEDULER_TOLERANCE``` and overridden by the API.

**Comment by bogdanm** [comment]
> @bogdanm @autopulated, a non-0 default tolerance is necessary for efficient operation of minar. That's what enables the callback aggregation, which allows longer sleep periods and fewer wakeups.

That's 100% true and makes perfect sense, the thing that worries me here is the user interface. Personally, I don't think that someone who schedules a callback expects it to have a non-zero tolerance (that is, if they read the documentation and actually know that tolerance exists). The way I'd do this personally is to assume a default tolerance of 0 and provide a mechanism to change it at compile time, like `YOTTA_CFG_MINAR_DEFAULT_SCHEDULER_TOLERANCE ` suggested above (at the moment I don't see a lot of value in providing a way to change the default tolerance at run time).
If the default tolerance is not 0, another thing that we need to decide is a sensible default. As @bremoran already pointed out, different kinds of applications will need different defaults, so this decision is not an easy one.
Another thing we need to consider is changing existing behaviour. If we change the value of the default tolerance, some applications that work now might suddently stop working with this change in place. It might even make sense to release a new major version of `minar` if we decide to change the default tolerance to prevent this kind of issue.

**Comment by autopulated** [comment]
I don't think the default should necessarily be configurable: if an individual callback needs a specific precision, then it should be specified when it's posted.

if your module is relying on the default being configured in a particular way, then you are relying on the application developer (who is ultimately in control of configuration) understanding the details of your module, which could conceivably conflict with those of other modules they want to use, so I don't think making the default configurable is really helpful here.

**Comment by bogdanm** [comment]
> I don't think the default should necessarily be configurable: if an individual callback needs a specific precision, then it should be specified when it's posted.

I could go with this. In this case, wouldn't it make more sense to make the default `0` rather than some pseudo-arbitrary value?

**Comment by bremoran** [comment]
@bogdanm I don't think so. It should be non-zero by default, since minar needs that for callback aggregation.

**Comment by bogdanm** [comment]
@bremoran, definitely, i'm not debating that, I'm just looking at this from the user interface perspective rather than the functionality perspective. I still think this can be a WTF factor for many users.

**Comment by autopulated** [comment]
The reasoning for the default to be non-zero was: ~~developers are~~ I am lazy, I will avoid specifying something if I don't have to, but there should normally be a tolerance specified since this has the benefits discussed, so therefore there should be a default tolerance. It also seems likely that more knowledgable/experienced developers will be dealing with things that need precise timing (and capable of specifying it exactly), and less less knowledgeable ones generally not needing to, and being less likely to understand/care about the optimisations afforded by the tolerance, they are unlikely to add one.

**Comment by autopulated** [comment]
Probably one for @hugovincent?

**Comment by hugovincent** [comment]
> if the default tolerance [is 0], this needs to be documented in big bold letters.

Yes, I agree with that.

We want people to be scheduling most stuff with a tolerance, and only specifying zero when they need it. If we make the default zero, we may as well remove timer coalescing altogether as no one will use it. If the default was much less than 50 ms (e.g. 1 ms), I would expect most users wouldn't notice that coalescing was happening and that would lead to confusing bugs (thus worse than zero). But if we made it much bigger (e.g. 1 second) so all users immediately notice that it's happening, then users will need to litter `.tolerance()`s throughout their code. I think where we are (50 ms) is a good middle ground between a useful amount of coalescing opportunity when the user doesn't specify or care, while not requiring every single scheduled event to be `.tolerance()`ed. 

@autopulated point about composability across modules is also an important one.

FWIW, Linux chose 50 microseconds as the default (http://man7.org/linux/man-pages/man2/prctl.2.html -- search for `TIMERSLACK`; more discussion [here](https://lwn.net/Articles/463357/) and [here](http://blog.qt.io/blog/2010/07/13/when-being-wrong-is-right/). Many Linux GUI programs set it to around 100 ms).
