### ISSUE TITLE
minar::scheduler::postCallback() from ISR

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/minar#30]
Is it possible to schedule callbacks from an interrupt context?

When doing this we're seeing that the pool fills up and it consequently tries to increase the pool size, which at some point fails.

**Comment by bogdanm** [comment]
Hi,

Yes, you're supposed to be able to schedule callbacks from an interrupt context. Do you have a sequence of code that can be used to reproduce the issue you're seeing?

Thanks,
Bogdan

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2082
