### ISSUE TITLE
minar starts continuously allocating memory for CallbackNodes 

### ISSUE THREAD

**Issue by markus-ender-tridonic-com** [ARMmbed/minar#33]
When mbed runs a while and uses minar heavily (one periodic event and several one-shot events),
after a time (hours) minar starts to allocate new pools for CallbackNodes. Not just one, but one after another until there is no space left on the heap.
Then mbed prints out this message and stops execution:
"Runtime error in file C:/IoT_WS/mbedos/gl-apps/tri-stc-driver-acdc/yotta_modules/minar/minar-internal-headers/CallbackNode.h, line 68: Unable to allocate CallbackNode"

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2129

**Comment by bogdanm** [comment]
Hi,

Thanks for the report. Can you share some code that can be used to reproduce this issue?

Thanks,
Bogdan

**Comment by markus-ender-tridonic-com** [comment]
I'm working on a test-code to reproduce this problem - and at the moment it looks like this is just a secondary problem and not the fault of Minar. So please ignore this issue until we have done some 	continuous tests and can provide more information.

**Comment by markus-ender-tridonic-com** [comment]
Ok, my investigations have shown that this is no Minar issue. Please excuse the false alarm.
