### ISSUE TITLE
assertion failed: ticks < minar:: platform::Time_Mask

### ISSUE THREAD

**Issue by cyliangtw** [ARMmbed/minar#44]
It's sal-iface-6lowpan test code socket initialization with timeout="-1" (i.e means never timeout ), so the socket or TCP stack convert this timeout milliseconds as tick. Finally stop at 
`CORE_UTIL_ASSERT(ticks < minar::platform::Time_Mask);`

After traced minar::milliseconds(), ticks is 64 bits by (32 bits input parameter milliseconds \* Time_Base/1000) and it will get assertion again as while input millisecond greater than 0x7FFFFFF in FRDM-K64F target.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2454

**Comment by betzw** [comment]
Isn't this rather a sal-iface-6lowpan problem?
I mean a timeout of -1 should never be converted in ticks ...

**Comment by cyliangtw** [comment]
If -1 can't be one valid input value of milliseconds(), I will regard it as sal-iface-6lowpan issue as below snippet of ns_sal.c: 

```
uint32_t ns_sal_socket_periodic_interval(...)
{
    if (SOCKET_STREAM == socket->family) {
        return 0xffffffff;
    }
    return 0;
}

```

**Comment by betzw** [comment]
Most likely, as the function `ns_sal_socket_periodic_interval(...)` should return the period with which a function should be called periodically. So - beyond the naming of variables - it's not a timeout for e.g. how long to wait or block before returning, where `-1` might have the meaning of "infinitely".

**Comment by betzw** [comment]
I am wondering another thing: why is the value of `minar::platform::Time_Mask` equal to `0x7FFFFFFF`, it should normally be `0xFFFFFFFF`?
(But this is obviously only a curiosity of mine)

**Comment by cyliangtw** [comment]
In FRDM-K64F case, Time_Mask is 0xFFFFFF & Time_Base is 0x8000.
According to the equation of ticks:
`ticks = (((uint64_t) milliseconds) * ((uint64_t) minar::platform::Time_Base)) / 1000`

 As while input `millisecond >= 0x7FFFFFF`, ticks will reach 0xFFFFFFFF.

**Comment by cyliangtw** [comment]
sal-iface-6lowpan new patch #2.1.1 https://github.com/ARMmbed/sal-iface-6lowpan/commit/eeabdd6aefa93a1167f97e06782f5e287dc93ab9 will fix it. 
This patch will reduce `ns_sal_socket_periodic_interval()` return value under 0xFFFFF.
